spring.application.name=IDE
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.datasource.url=jdbc:mysql://localhost:3306/PBL_5
spring.datasource.username=root
spring.datasource.password=loinguyen

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=PBL_5_secret_key_2025_2026_HK2_23T_NHAT1_2023_2027
jwt.expiration-ms=86400000

docker.image.name=image:v1

#ai.model.base-url=https://outsource-growing-glamour.ngrok-free.dev
ai.model.base-url=http://192.168.137.76:8000
